export const playerFetchActions = {
  PLAYER_FETCH_REQUESTED: "PLAYER_FETCH_REQUESTED",
  PLAYER_FETCH_SUCCEEDED: "PLAYER_FETCH_SUCCEEDED",
  PLAYER_FETCH_FAILED: "PLAYER_FETCH_FAILED",
  CHEST_FETCH_REQUESTED: "CHEST_FETCH_REQUESTED",
  CHEST_FETCH_SUCCEEDED: "CHEST_FETCH_SUCCEEDED"
};
